FROM mcr.microsoft.com/devcontainers/typescript-node:18

# [Optional] Uncomment this section to install additional OS packages.
RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    apt-get upgrade -y
    # apt-get -y install --no-install-recommends <your-package-list-here>